# Generated by Django 2.2.7 on 2019-11-14 12:45

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191114_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/category-backgrounds'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/services'),
        ),
    ]
